ci: update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,12 +39,12 @@ jobs:
         run: npm run test:coverage
         working-directory: .
 
-      - name: Prepare Coverage Report
-        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
-        run: |
-          cp coverage/lcov-report/index.html coverage/index.html
-          echo "<!DOCTYPE html><html><body><h1>Coverage Report</h1><p><a href=\"lcov-report/index.html\">View Coverage</a></p></body></html>" > coverage/index.html
-        working-directory: .
+      # - name: Prepare Coverage Report
+      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     cp coverage/lcov-report/index.html coverage/index.html
+      #     echo "<!DOCTYPE html><html><body><h1>Coverage Report</h1><p><a href=\"lcov-report/index.html\">View Coverage</a></p></body></html>" > coverage/index.html
+      #   working-directory: .
 
       - name: Upload Coverage Report Artifact
         if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
@@ -52,47 +52,47 @@ jobs:
         with:
           path: coverage/
 
-  deploy:
-    runs-on: ubuntu-latest
-    if: always()
-    needs: test
-    permissions:
-      pages: write
-      id-token: write
-    environment:
-      name: github-pages-app
-      url: https://tadeu-dutra.github.io/string-search-app/index.html
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          path: .
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   if: always()
+  #   needs: test
+  #   permissions:
+  #     pages: write
+  #     id-token: write
+  #   environment:
+  #     name: github-pages-app
+  #     url: https://tadeu-dutra.github.io/string-search-app/index.html
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         path: .
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '18'
-          cache: 'npm'
-          cache-dependency-path: package.json
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '18'
+  #         cache: 'npm'
+  #         cache-dependency-path: package.json
 
-      - name: Install dependencies
-        run: npm install
-        working-directory: .
+  #     - name: Install dependencies
+  #       run: npm install
+  #       working-directory: .
 
-      # - name: Build Web Application
-      #   run: |
-      #     npm run build || { echo "Build failed"; exit 1; }
-      #     ls -la dist/ || echo "dist/ directory not found after build"
-      #   working-directory: .
+  #     # - name: Build Web Application
+  #     #   run: |
+  #     #     npm run build || { echo "Build failed"; exit 1; }
+  #     #     ls -la dist/ || echo "dist/ directory not found after build"
+  #     #   working-directory: .
       
-      - name: Upload pages artifact
-        uses: actions/upload-pages-artifact@v3
-        with:
-          path: dist/
+  #     - name: Upload pages artifact
+  #       uses: actions/upload-pages-artifact@v3
+  #       with:
+  #         path: dist/
       
-      # - name: Deploy to GitHub Pages
-      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
-      #   uses: actions/deploy-pages@v4
+  #     # - name: Deploy to GitHub Pages
+  #     #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
+  #     #   uses: actions/deploy-pages@v4
 
 
 
