ci: update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -80,11 +80,13 @@ jobs:
         working-directory: .
 
       - name: Build Web Application
-        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
-        run: |
-          npm run build || { echo "Build failed"; exit 1; }
-          ls -la dist/ || echo "dist/ directory not found after build"
-        working-directory: .
+        run: npm run build
+        
+        # if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
+        # run: |
+        #   npm run build || { echo "Build failed"; exit 1; }
+        #   ls -la dist/ || echo "dist/ directory not found after build"
+        # working-directory: .
 
       # - name: Download Coverage Artifact
       #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
@@ -93,12 +95,12 @@ jobs:
       #     name: github-pages-artifact-test  # Default name for upload-pages-artifact
       #     path: coverage/
 
-      - name: Prepare Web Application and Coverage
-        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
-        run: |
-          mkdir -p public
-          if [ -d "dist/" ]; then cp -r dist/* public/; else echo "dist/ not found, skipping copy"; fi
-        working-directory: .
+      # - name: Prepare Web Application and Coverage
+      #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     mkdir -p public
+      #     if [ -d "dist/" ]; then cp -r dist/* public/; else echo "dist/ not found, skipping copy"; fi
+      #   working-directory: .
 
       # - name: Prepare Coverage Report
       #   if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
@@ -117,4 +119,4 @@ jobs:
         if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
         uses: actions/deploy-pages@v4
         with:
-          path: public/
+          path: dist/
